/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StockTransfersRouteImport } from './routes/stock.transfers'
import { Route as StockInventoryRouteImport } from './routes/stock.inventory'
import { Route as OpsProductionRouteImport } from './routes/ops.production'
import { Route as OpsOrdersRouteImport } from './routes/ops.orders'
import { Route as CrmTicketsRouteImport } from './routes/crm.tickets'
import { Route as CrmPipelineRouteImport } from './routes/crm.pipeline'
import { Route as CrmClientsRouteImport } from './routes/crm.clients'
import { Route as CrmClientsClientIdRouteImport } from './routes/crm.clients.$clientId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockTransfersRoute = StockTransfersRouteImport.update({
  id: '/stock/transfers',
  path: '/stock/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const StockInventoryRoute = StockInventoryRouteImport.update({
  id: '/stock/inventory',
  path: '/stock/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsProductionRoute = OpsProductionRouteImport.update({
  id: '/ops/production',
  path: '/ops/production',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsOrdersRoute = OpsOrdersRouteImport.update({
  id: '/ops/orders',
  path: '/ops/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmTicketsRoute = CrmTicketsRouteImport.update({
  id: '/crm/tickets',
  path: '/crm/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmPipelineRoute = CrmPipelineRouteImport.update({
  id: '/crm/pipeline',
  path: '/crm/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmClientsRoute = CrmClientsRouteImport.update({
  id: '/crm/clients',
  path: '/crm/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmClientsClientIdRoute = CrmClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => CrmClientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/crm/clients': typeof CrmClientsRouteWithChildren
  '/crm/pipeline': typeof CrmPipelineRoute
  '/crm/tickets': typeof CrmTicketsRoute
  '/ops/orders': typeof OpsOrdersRoute
  '/ops/production': typeof OpsProductionRoute
  '/stock/inventory': typeof StockInventoryRoute
  '/stock/transfers': typeof StockTransfersRoute
  '/crm/clients/$clientId': typeof CrmClientsClientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/crm/clients': typeof CrmClientsRouteWithChildren
  '/crm/pipeline': typeof CrmPipelineRoute
  '/crm/tickets': typeof CrmTicketsRoute
  '/ops/orders': typeof OpsOrdersRoute
  '/ops/production': typeof OpsProductionRoute
  '/stock/inventory': typeof StockInventoryRoute
  '/stock/transfers': typeof StockTransfersRoute
  '/crm/clients/$clientId': typeof CrmClientsClientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/crm/clients': typeof CrmClientsRouteWithChildren
  '/crm/pipeline': typeof CrmPipelineRoute
  '/crm/tickets': typeof CrmTicketsRoute
  '/ops/orders': typeof OpsOrdersRoute
  '/ops/production': typeof OpsProductionRoute
  '/stock/inventory': typeof StockInventoryRoute
  '/stock/transfers': typeof StockTransfersRoute
  '/crm/clients/$clientId': typeof CrmClientsClientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/dashboard'
    | '/login'
    | '/crm/clients'
    | '/crm/pipeline'
    | '/crm/tickets'
    | '/ops/orders'
    | '/ops/production'
    | '/stock/inventory'
    | '/stock/transfers'
    | '/crm/clients/$clientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/dashboard'
    | '/login'
    | '/crm/clients'
    | '/crm/pipeline'
    | '/crm/tickets'
    | '/ops/orders'
    | '/ops/production'
    | '/stock/inventory'
    | '/stock/transfers'
    | '/crm/clients/$clientId'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/dashboard'
    | '/login'
    | '/crm/clients'
    | '/crm/pipeline'
    | '/crm/tickets'
    | '/ops/orders'
    | '/ops/production'
    | '/stock/inventory'
    | '/stock/transfers'
    | '/crm/clients/$clientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  CrmClientsRoute: typeof CrmClientsRouteWithChildren
  CrmPipelineRoute: typeof CrmPipelineRoute
  CrmTicketsRoute: typeof CrmTicketsRoute
  OpsOrdersRoute: typeof OpsOrdersRoute
  OpsProductionRoute: typeof OpsProductionRoute
  StockInventoryRoute: typeof StockInventoryRoute
  StockTransfersRoute: typeof StockTransfersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/transfers': {
      id: '/stock/transfers'
      path: '/stock/transfers'
      fullPath: '/stock/transfers'
      preLoaderRoute: typeof StockTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/inventory': {
      id: '/stock/inventory'
      path: '/stock/inventory'
      fullPath: '/stock/inventory'
      preLoaderRoute: typeof StockInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/production': {
      id: '/ops/production'
      path: '/ops/production'
      fullPath: '/ops/production'
      preLoaderRoute: typeof OpsProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/orders': {
      id: '/ops/orders'
      path: '/ops/orders'
      fullPath: '/ops/orders'
      preLoaderRoute: typeof OpsOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/tickets': {
      id: '/crm/tickets'
      path: '/crm/tickets'
      fullPath: '/crm/tickets'
      preLoaderRoute: typeof CrmTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/pipeline': {
      id: '/crm/pipeline'
      path: '/crm/pipeline'
      fullPath: '/crm/pipeline'
      preLoaderRoute: typeof CrmPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/clients': {
      id: '/crm/clients'
      path: '/crm/clients'
      fullPath: '/crm/clients'
      preLoaderRoute: typeof CrmClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/clients/$clientId': {
      id: '/crm/clients/$clientId'
      path: '/$clientId'
      fullPath: '/crm/clients/$clientId'
      preLoaderRoute: typeof CrmClientsClientIdRouteImport
      parentRoute: typeof CrmClientsRoute
    }
  }
}

interface CrmClientsRouteChildren {
  CrmClientsClientIdRoute: typeof CrmClientsClientIdRoute
}

const CrmClientsRouteChildren: CrmClientsRouteChildren = {
  CrmClientsClientIdRoute: CrmClientsClientIdRoute,
}

const CrmClientsRouteWithChildren = CrmClientsRoute._addFileChildren(
  CrmClientsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  CrmClientsRoute: CrmClientsRouteWithChildren,
  CrmPipelineRoute: CrmPipelineRoute,
  CrmTicketsRoute: CrmTicketsRoute,
  OpsOrdersRoute: OpsOrdersRoute,
  OpsProductionRoute: OpsProductionRoute,
  StockInventoryRoute: StockInventoryRoute,
  StockTransfersRoute: StockTransfersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
